export const UPDATE_POSTS = 'UPDATE_POSTS';


// login action types
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';


export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const LOG_OUT = 'LOG_OUT';
export const CLEAR_AUTH_ERROR_STATE = 'CLEAR_AUTH_ERROR_STATE';


export const EDIT_PROFILE_SUCCESSFUL = 'EDIT_PROFILE_SUCCESSFUL';
export const EDIT_PROFILE_FAILED = 'EDIT_PROFILE_FAILED';


export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAILED = 'USER_PROFILE_FAILED';
export const FETCH_USER_PROFILE = 'FETCH_USER_PROFILE'; 

// friends
export const FETCH_FRIENDS_SUCCESS = 'FETCH_FRIENDS_SUCCESS';
export const ADD_FRIEND = 'ADD_FRIEND';
export const REMOVE_FRIEND = 'REMOVE_FRIEND';  


export const ADD_POST = 'ADD_POST'; 
export const ADD_COMMENT = 'ADD_COMMENT';


// search 
export const FETCH_SEARCH_RESULT = 'FETCH_SEARCH_RESULT';

